Labster/fix/get user roles in courseware
Bodekaer/Labster.EdX pull request #65
Opened 2017-02-13 08:04 UTC by lukyfebrianto

FIX WEB 794

2017-02-13 11:15 UTC, polesye requested changes

2017-02-13 11:15 UTC, polesye commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +        )
Please add empty line at the end.

2017-02-13 11:15 UTC, polesye commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +        self.course_instructor2 = InstructorFactory(course_key=self.course2.id, password="test")
we should use Coaches instead of Instuctors

2017-02-14 12:22 UTC, lukyfebrianto commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +        self.course_instructor2 = InstructorFactory(course_key=self.course2.id, password="test")
Done, Thank you

2017-02-14 12:44 UTC, polesye commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +    def make_ccx(self, coach, course, display_name):
Cannot we simply inherit those 2 method from https://github.com/Livit/Livit.Learn.EdX/blob/labster/develop/openedx/core/djangoapps/labster/tests/base.py#L25 ?

2017-02-14 15:11 UTC, lukyfebrianto commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +    def make_ccx(self, coach, course, display_name):
I don't think so @polesye  because in that method designed for one user and one course. This test method is simply when we want add another ccx or coach and when we have more than one user just like flow of this issue.. CMIIW. What do you think @polesye ?

2017-02-15 09:24 UTC, TamoshaytisV commented
please add `WEB-794` to the PR title

2017-02-15 10:40 UTC, TamoshaytisV commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +# pylint: disable=protected-access
Do you really need this pylint suppression?

2017-02-15 10:40 UTC, TamoshaytisV commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +        Set up tests
don't forget dots in the end of docstrings :)

2017-02-15 10:40 UTC, TamoshaytisV commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +        Create ccx
Create ccx`.`

2017-02-15 10:40 UTC, TamoshaytisV commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +
remove empty line

2017-02-16 04:58 UTC, lukyfebrianto commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +# pylint: disable=protected-access
Got it, we don't need it :). 
Done

2017-02-16 04:58 UTC, lukyfebrianto commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +        Create ccx
Done

2017-02-16 04:58 UTC, lukyfebrianto commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +        Set up tests
Done

2017-02-16 04:59 UTC, lukyfebrianto commented on lms/djangoapps/courseware/tests/test_access_labster.py
> +
Done

2017-02-16 09:23 UTC, TamoshaytisV approved these changes
looks ok to me :)

2017-02-20 07:17 UTC, polesye approved these changes
Looks good to merge. Please make sure it works as expected before merging.

2017-02-20 07:45 UTC, merged