WEB-727 Show only licensed simulations
Bodekaer/Labster.EdX pull request #67
Opened 2017-02-27 23:44 UTC by TamoshaytisV

This PR is a result of the approach to change existing logic of processing courseware items visibility.

## Problem description
Currently, we have an issue with newly added master course (MC) content. Every added extra simulation will appear in every CCX course derived from MC even if it is not present in the license. The current workaround is to reapply licenses for every CCX course which can be very irritating.

## PR implementation idea
When license is applied, we store info about the course: list of licensed simulations from API for course (licensed sims cache), store licensed simulations per every courseware block. Write custom override provider that will return `visible_to_staff_only` property value `True` if no licensed simulations in block and no another not licensed content (html, problem, overview), otherwise `False`.
Catch `course_published signal` and update saved course access info according to course licensed simulations chache (no additional API requests).

2017-03-03 14:17 UTC, polesye requested changes

2017-03-03 14:17 UTC, polesye commented on lms/envs/labster.py
> +    'lms.djangoapps.labster_course_license.licensed_blocks_override.LicensedBlocksOverrideProvider',
How does it work together with https://github.com/Livit/Livit.Learn.EdX/blob/7f57a8045159f9e12df1c710fd02b35d060fa630/lms/envs/aws.py#L689-L691 ?

According to https://github.com/Livit/Livit.Learn.EdX/blob/labster/develop/lms/djangoapps/courseware/field_overrides.py#L126 it stops loop when the 1st provider returns some value. Can we guarantee correctness in this case?

2017-03-03 14:17 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +                if len(set(block_simulations) & set(lci_simulations)) != len(block_simulations):
Why not simply?
```py
if set(block_simulations) ^ set(lci_simulations):
```

2017-03-03 14:17 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +        apply_field_overrides(ccx, simulations, licensed_simulations)
Why do we need to apply field overrides here?

2017-03-03 14:17 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +            override_field_for_ccx(ccx, sim, field_name, True)
Don't we need to use `clear_override_for_ccx` to fix issue descibed above?

2017-03-03 14:17 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        return False
Does it make sense to return `default` here, so it will inherit value from the master course?

2017-03-03 14:17 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +                        return False
same as above

2017-03-03 14:17 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +                        return False
Why do we need this check?

2017-03-03 14:17 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +            lic_sims = cls.objects.create(course_license=course_license)
`get_or_create`?

2017-03-03 14:17 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +    licensed_simulations = models.TextField(blank=True, null=True)
Doesn't it looks like duplication of data between models `LicensedSimulations` and `LicensedCoursewareItems`?

2017-03-03 14:18 UTC, polesye requested changes

2017-03-03 14:18 UTC, polesye commented on lms/djangoapps/labster_course_license/tasks.py
> +        for ccx in custom_courses:
I thought we're going to avoid this iteration though the list of all CCX courses. Can we avoid it somehow?

2017-03-03 18:53 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        courseware_item = LicensedCoursewareItems.objects.get(block=block.location.block_id)
I'm thinking about using cache to reduce amount of calls to DB.

2017-03-16 01:14 UTC, TamoshaytisV commented
@polesye @leha2000 please review

2017-03-16 08:43 UTC, polesye requested changes

2017-03-16 08:43 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +        course_license, __ = cls.objects.get_or_create(course_id=course_id, license_code=license_code)
you should override previous license, you should use `defaults` here
```py
course_license, __ = cls.objects.get_or_create(course_id=course_id, defaults={'license_code': license_code})
```

2017-03-16 08:43 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +        return unicode("%s, %s" % (self.course_id, self.license_code))
Are you sure it's descriptive enough?

2017-03-16 08:43 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +    simulations = JSONField()
add help text

2017-03-16 08:43 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +        return unicode("%s, %s" % (self.block, self.simulations))
Are you sure it's descriptive enough?

2017-03-16 08:43 UTC, polesye commented on lms/djangoapps/labster_course_license/signals.py
> +    log.info(u'Added task to update access course structure for course "%s" to the task queue', course_key)
Isn't it logged in Celery log by default?

2017-03-16 09:12 UTC, polesye commented on lms/urls.py
> +    url(r'^labster_license/', include('labster_course_license.webhook_urls')),
why separate file? Why don't you use `urls.py`?

2017-03-16 09:17 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +            )
I'm not sure how it will affect API.

2017-03-16 09:18 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +            )
It's common case that API has much more licenses than edX, so does it make sense to repsonse with 400 error?

2017-03-16 09:18 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +                status=status.HTTP_400_BAD_REQUEST
I'm not sure how it will affect API. @leha2000 FYI

2017-03-16 09:20 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +    permission_classes = (IsAuthenticated,)
Probably `IsAdminUser` better idea to user, otherwise everyone can use this view.

2017-03-16 09:22 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +    simulations = JSONField()
please add `modified_at`, `created_at` fields

2017-03-16 09:22 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
>      license_code = models.CharField(max_length=255, db_index=True)
please add `modified_at`, `created_at` fields if it's possible

2017-03-16 10:22 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +        course_license.simulations = request.data['licensed_simulations']
please use `licensed_simulations_ids = get_licensed_simulations(consumer_keys)` to get a list of actual simulations

2017-03-16 10:27 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +            log.error(msg, type(block))
do we need to return `default` here?

2017-03-16 10:30 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +    try:
please leave some comment about that

2017-03-16 10:30 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +    try:
please leave some comment about that

2017-03-16 10:32 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        return default
please leave a comment why `default` here

2017-03-16 10:36 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        return default
please leave a comment where do we handle situations when block doesn't contain any simulations.

2017-03-16 10:38 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +    simulations = JSONField()
please add help_text

2017-03-16 10:42 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        course_locator = course_key
do we really need to handle regular courses? Or we need to return `default` here?

2017-03-16 10:45 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +        return ret
Why do we need such changes?

2017-03-16 10:48 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
>          except cls.DoesNotExist:
https://docs.djangoproject.com/en/1.10/ref/exceptions/#objectdoesnotexist

2017-03-16 10:53 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +        course_license, __ = cls.objects.get_or_create(course_id=course_id, license_code=license_code)
it will produce MultipleObjectsError in provider

2017-03-16 10:55 UTC, polesye commented on lms/djangoapps/labster_course_license/models.py
> +    course_id = CourseKeyField(max_length=255, db_index=True)
add help_text
CCXCourseLocators only

2017-03-16 10:57 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        course_license = CourseLicense.objects.get(course_id=course_locator)
please use `course_key` instead of `course_locator`. We should only work with CCX courses

2017-03-16 10:58 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        course_license = CourseLicense.objects.get(course_id=course_locator)
By CCX_KEY find License for this CCX

2017-03-21 09:33 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +                    course_key = CCXLocator.from_course_locator(course_key, ccx.id)
let's use `ccx_key` that is more correct and clear.

2017-03-21 09:34 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        location = block.location
so why do we use `block.location` here. According to the comment `# just `block.location` will result in all courseware items are shown` ?

2017-03-21 09:35 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +    # this will allow to stay in sync with studio visibility edits
is it a correct place for this comment?

2017-03-21 09:37 UTC, polesye commented on lms/djangoapps/labster_course_license/tests/factories.py
> +    course_id = CourseLocator(org='edX', course='toy', run='2012_Fall')
Should we revert this line?

2017-03-21 09:38 UTC, polesye commented on lms/djangoapps/labster_course_license/tests/test_views.py
> +    def is_visible_to_staff_only(self, block):
why do we need this method? Remove?

2017-03-22 01:38 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/tests/test_views.py
> +    def is_visible_to_staff_only(self, block):
removed

2017-03-22 01:42 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/tests/factories.py
> +    course_id = CourseLocator(org='edX', course='toy', run='2012_Fall')
reverted

2017-03-22 01:42 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +    # this will allow to stay in sync with studio visibility edits
moved to provider `get` method

2017-03-22 01:43 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        location = block.location
changed comment
this logic is needed

2017-03-22 01:43 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +                    course_key = CCXLocator.from_course_locator(course_key, ccx.id)
changed

2017-03-22 01:43 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/models.py
> +    course_id = CourseKeyField(max_length=255, db_index=True)
added

2017-03-22 01:44 UTC, TamoshaytisV commented
@polesye @leha2000 please continue review

2017-03-22 11:45 UTC, polesye commented on lms/djangoapps/labster_course_license/webhook_urls.py
> +)
add empty line

2017-03-22 11:45 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +                {"error": "No license code was provided."}, status=status.HTTP_400_BAD_REQUEST
Is it possible?

2017-03-22 11:52 UTC, polesye commented on lms/djangoapps/labster_course_license/management/commands/update_course_licenses.py
> +                licensed_simulations_ids = get_licensed_simulations(consumer_keys)
you know it may DDOS API server. Is there other way to do that? using 1 request, json etc?

2017-03-22 11:53 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +        if name != 'visible_to_staff_only':
How the comment above is related to this line of code?

2017-03-22 11:54 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +    # not all blocks locations are BlockUsageLocator's
`for example: ... `

2017-03-23 07:51 UTC, leha2000 requested changes

2017-03-23 07:51 UTC, leha2000 commented on lms/djangoapps/labster_course_license/models.py
> +        except ObjectDoesNotExist:
Why is it changed like this?

2017-03-23 07:51 UTC, leha2000 commented on lms/djangoapps/labster_course_license/models.py
> +        course_license, __ = cls.objects.get_or_create(
It doesn't update the license_code if the `course_license` exists already so please add the code below:
```
course_license, created = cls.objects.get_or_create(...)
if not created:
    course_license.license_code = license_code
    course_license.save()
```

Also please add the test for this

2017-03-23 07:51 UTC, leha2000 commented on lms/djangoapps/labster_course_license/tasks.py
> +        for block, block_simulations in course_info.items():
What if some blocks are deleted?
Does it make sense to store course Id in the `LicensedCoursewareItems` and then delete all the `LicensedCoursewareItems` by the course and block that isn't in the `course_info`?

2017-03-23 07:51 UTC, leha2000 commented on lms/djangoapps/labster_course_license/utils.py
> +        course_key = block.id
Why don't just return `course_key` in each if? Then we don't need `else: return None`

2017-03-23 07:51 UTC, leha2000 commented on lms/djangoapps/labster_course_license/utils.py
> +    if not block_simulations and not isinstance(block_simulations, set):
Is this case `not isinstance(block_simulations, set)` real?

2017-03-23 07:51 UTC, leha2000 commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +                    ccx_key = CCXLocator.from_course_locator(course_key, ccx.id)
Does this always return `ccx_key is not None` or raises exception?

2017-03-23 08:30 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +            )
@leha2000 FYI^^
I think we should respond with `Response(status=status.HTTP_200_OK)`, so it means that edX recieved information about License and it's up to edX to decide what to do with it.

2017-03-23 19:39 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +                    ccx_key = CCXLocator.from_course_locator(course_key, ccx.id)
`ccx = get_current_ccx(course_key)` raises exception
ccx_key is always not None

2017-03-23 19:42 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/utils.py
> +    if not block_simulations and not isinstance(block_simulations, set):
removed

2017-03-23 19:42 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/utils.py
> +        course_key = block.id
refactored

2017-03-23 19:44 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/models.py
> +        course_license, __ = cls.objects.get_or_create(
added

2017-03-23 19:45 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/models.py
> +        except ObjectDoesNotExist:
because for some reason 39 line could return DoesNotExist object and we get `DoesNotExist object is not callable` exception

2017-03-23 19:58 UTC, polesye commented on lms/urls.py
> +    url(r'^labster_license/', include('labster_course_license.webhook_urls')),
@TamoshaytisV ^^

2017-03-23 20:50 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/tasks.py
> +        for block, block_simulations in course_info.items():
added remove unused blocks

2017-03-23 20:55 UTC, TamoshaytisV commented on lms/urls.py
> +    url(r'^labster_license/', include('labster_course_license.webhook_urls')),
because we will have url like `api/courses/some_course_id/license_update` then. It's ok for edx but not for API webhook because of `some_course_id`

2017-03-24 11:17 UTC, leha2000 commented on lms/djangoapps/labster_course_license/views.py
> +            )
Yes. We can return 200 OK

2017-03-24 12:27 UTC, leha2000 approved these changes

2017-03-24 17:06 UTC, polesye commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +    print(actual_simulations.intersection(available_simulations))
@TamoshaytisV remove prints

2017-03-24 17:12 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +            )
@TamoshaytisV FYI^^

2017-03-24 17:14 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +        ccx = CustomCourseForEdX.objects.get(pk=ccx_id)
Are you sure the course exists?
What if it has been removed? In this case, course_license is still exist.

2017-03-24 17:16 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
> +            )
Same as about. status code 200 has to be returned.
Webhook doesn't care about result, its responsibility just inform services.

2017-03-24 17:17 UTC, polesye commented on lms/urls.py
> +    url(r'^labster_license/', include('labster_course_license.webhook_urls')),
got you

2017-03-25 07:56 UTC, polesye commented
@sidorovdmitry Can you check why there is no checks: tests, pylint, pep8?

2017-03-26 22:54 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/views.py
> +            )
changed to return 200_OK

2017-03-26 22:55 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/views.py
> +        ccx = CustomCourseForEdX.objects.get(pk=ccx_id)
Added exception processing

2017-03-26 22:55 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/licensed_blocks_override.py
> +    print(actual_simulations.intersection(available_simulations))
removed

2017-03-27 05:52 UTC, polesye commented on lms/djangoapps/labster_course_license/views.py
>              log.error("Failed to update course license %s simulations" % course_license)
In this case, error message should be more meaningful. It says nothing about the reason of the issue.

2017-03-27 06:17 UTC, polesye commented on lms/djangoapps/labster_course_license/management/commands/update_course_licenses.py
> +            licensed_simulations_ids = data.get(course_license.license_code)
what if it doesn't exist? Should we stop the whole proccess?

2017-03-27 06:17 UTC, polesye commented on lms/djangoapps/labster_course_license/management/commands/update_course_licenses.py
> +            ccx = CustomCourseForEdX.objects.get(pk=ccx_id)
are you sure the course always exists?

2017-03-30 16:28 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/management/commands/update_course_licenses.py
> +            ccx = CustomCourseForEdX.objects.get(pk=ccx_id)
added exception handling

2017-03-30 16:29 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/management/commands/update_course_licenses.py
> +            licensed_simulations_ids = data.get(course_license.license_code)
Nope, it will return just None
I process this case

2017-03-30 16:29 UTC, TamoshaytisV commented on lms/djangoapps/labster_course_license/views.py
>              log.error("Failed to update course license %s simulations" % course_license)
changed

2017-04-13 10:51 UTC, polesye approved these changes

2017-04-26 13:35 UTC, merged