Labster enrollment view
Bodekaer/Labster.EdX pull request #69
Opened 2017-03-25 09:08 UTC by polesye

This view helps automate enrollment workflow in the the new "direct to student" pricing experiments.
It's a copy of `ccx_invite` view with authentication adjustments (Token authentication is added).

@TamoshaytisV @lukyfebrianto please review. Could someone of you make sure tests pass on Dogwood release, because I didn't have a chance to run them locally?

@Bodekaer FYI.

2017-03-25 20:26 UTC, Bodekaer commented
Awesome! Thanks so much @polesye!

In terms of activating this new `ccx_invite` feature, I've been thinking about the best way to do it.
I can do it via PHP on the WP marketing website, but I'm also thinking that it would be a better architecture if our API handled this.
We have the Stripe webhook setup now here:
https://github.com/Livit/Livit.Learn.LTI/blob/edd8b58d92a5ee338ed5985058f555abe32076e4/django_project/payments/views.py

Would it be possible to have it detect a new Stripe subscription, and then call the new `ccx_invite` EdX method? Or do you prefer to keep it in the Marketing site? 
You can see the Stripe `customer.subscription.created` event details here:
https://stripe.com/docs/api#event_types-customer.subscription.created

2017-03-25 20:29 UTC, Bodekaer commented
We can just hardcode the CCX course ids and subscription ids (e.g. if subscription id = X, invite to CCX course Y).
Or alternatively make a simply `SubscriptionCourses` Django model/table with two fields: 
`stripeSubscriptionId`, `course_key`.

2017-03-27 06:54 UTC, polesye commented
@Bodekaer I'd prefer to keep it in the Marketing site atm, because it's more simple solution.

2017-03-27 10:45 UTC, lukyfebrianto reviewed
Please see my comment @polesye .CMIIW

2017-03-27 10:45 UTC, lukyfebrianto commented on openedx/core/djangoapps/labster/course/tests/test_views.py
> +        ccx = self.make_ccx(max_students_allowed=2)
did we have max_students_allowed args on make_ccx ?

2017-03-27 10:45 UTC, lukyfebrianto commented on openedx/core/djangoapps/labster/course/views.py
>  from rest_framework.permissions import IsAuthenticated
remove this if unused

2017-03-27 10:45 UTC, lukyfebrianto commented on openedx/core/djangoapps/labster/course/views.py
>  from rest_framework.reverse import reverse
remove this if unused

2017-03-27 10:45 UTC, lukyfebrianto commented on openedx/core/djangoapps/labster/course/views.py
> +@permission_classes((IsAdminUser,))
do we have import func for IsAdminUser ?

2017-03-27 10:45 UTC, lukyfebrianto commented on openedx/core/djangoapps/labster/course/views.py
>  def coach_list_handler(reuqest):
reuqest or request ?

2017-03-27 10:45 UTC, lukyfebrianto commented on openedx/core/djangoapps/labster/course/views.py
> +    email_students = 'email_students' in request.POST
do we need  this email_students ?

2017-03-27 10:45 UTC, lukyfebrianto commented on openedx/core/djangoapps/labster/course/views.py
> +@coach_dashboard
do we have import for this decorator?

2017-03-28 05:52 UTC, polesye commented on openedx/core/djangoapps/labster/course/views.py
> +    email_students = 'email_students' in request.POST
> do we need this email_students ?

Good catch. Removed.

2017-03-28 05:52 UTC, polesye commented on openedx/core/djangoapps/labster/course/views.py
> +@coach_dashboard
> do we have import for this decorator?

Typo, fixed.

2017-03-28 05:52 UTC, polesye commented on openedx/core/djangoapps/labster/course/views.py
>  def coach_list_handler(reuqest):
> reuqest or request ?

typo is fixed

2017-03-28 05:52 UTC, polesye commented on openedx/core/djangoapps/labster/course/views.py
> +@permission_classes((IsAdminUser,))
> do we have import func for IsAdminUser ?

Fixed

2017-03-28 05:53 UTC, polesye commented on openedx/core/djangoapps/labster/course/views.py
>  from rest_framework.reverse import reverse
> remove this if unused

Done

2017-03-28 05:53 UTC, polesye commented on openedx/core/djangoapps/labster/course/views.py
>  from rest_framework.permissions import IsAuthenticated
> remove this if unused

Done

2017-03-28 05:53 UTC, polesye commented on openedx/core/djangoapps/labster/course/tests/test_views.py
> +        ccx = self.make_ccx(max_students_allowed=2)
> did we have max_students_allowed args on make_ccx ?

Good point, extended.

2017-03-28 05:53 UTC, polesye commented
@lukyfebrianto @TamoshaytisV I've addressed comments. Please continue review.

2017-03-28 13:17 UTC, TamoshaytisV requested changes
You've replaced
```
-        return CcxFactory(course_id=self.course.id, coach=self.user)
```
to
```
 +        ccx = CcxFactory(course_id=self.course.id, coach=self.coach)
```
but there is no self.coach class field

2017-03-30 06:13 UTC, polesye commented on lms/djangoapps/labster_enroll/views.py
> +            "course_key": "course-v1:labster+LABX+2015_T1",
remove this line, it's a part of url

2017-03-30 06:13 UTC, polesye commented on lms/djangoapps/labster_enroll/views.py
> +        POST /labster/api/course/enroll
please fix url format, it should include course key

2017-03-30 11:46 UTC, TamoshaytisV commented
@lukyfebrianto @polesye please finish review

2017-03-30 11:47 UTC, TamoshaytisV approved these changes

2017-03-31 05:55 UTC, lukyfebrianto approved these changes
Looks good to me

2017-03-31 09:30 UTC, merged