WEB-1701 Unable to apply Vouchers in Staging
Bodekaer/Labster.EdX pull request #71
Opened 2017-06-06 06:51 UTC by lukyfebrianto

**Description:** Unable to apply Vouchers in Staging

**JIRA:**  https://liv-it.atlassian.net/browse/WEB-1701

**Merge deadline:** N/A

**Testing instructions:**

Steps to reproduce:
1. Create License (mine:Mk9qXoero4hWeq1MvdRWxwYexMVs) 
2. Apply new license in a new course (Teacher: elvana+119@labster.com) 
3. Create vouchers 
4. Login as student (Student: elvana+50@labster.com) 
5. Enter Voucher (Voucher:GF8JEGN2W2 or 8M4GFCBOWI)

**Reviewers:**
- [x] @TamoshaytisV  
- [x] @leha2000 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Delete working branch (if not needed anymore)

2017-06-06 23:52 UTC, TamoshaytisV requested changes
Luky, i think we have this situation because i've set "Invitation only" on staging. Even if we set that flag to `false` we could still have it cached. But on prod we have no such situation. So my question is: isn't it better to have some kind of management command or execute code in shell instead of updating cache every voucher apply? What do you think?

2017-06-06 23:52 UTC, TamoshaytisV commented on lms/djangoapps/labster_vouchers/views.py
> +    course_key = SlashSeparatedCourseKey.from_deprecated_string(unicode(course_id))
can we assign `unicode(course_id)` to variable only once and use the result?

2017-06-07 06:15 UTC, lukyfebrianto commented on lms/djangoapps/labster_vouchers/views.py
> +    course_key = SlashSeparatedCourseKey.from_deprecated_string(unicode(course_id))
Ahh, I see so it isn't common situation. Yes agree with it but isn't better to update `invitation_only` through admin panel  i.e: https://staging-studio-courses.labster.com/admin/course_overviews/courseoverview/ ?

2017-06-07 08:19 UTC, leha2000 approved these changes

2017-06-08 07:00 UTC, lukyfebrianto commented
FYI: 
I do some test that @TamoshaytisV told me as follows,
- to turn it on again for course in studio
- confirm that vouchers could not be applied (failed)
- turn off flag in studio 
- turn off flag in course overview 
- confirm vouchers work 

I found that step "confirm that vouchers could not be applied" not working so I change the code on studio so when user update through settings on studio it will synchronize data between course module and course_overview.

2017-06-08 16:16 UTC, lukyfebrianto commented on cms/djangoapps/contentstore/views/course.py
> +                            course_overview = CourseOverview.objects.get(id=course_key)
Check if course data is exist in courseOverview model

2017-06-12 06:58 UTC, closed without merging